version: '3'

services:
  api:
    build: ./SmartMarketPlace_backend
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:5432"
    container_name: smp-back
    volumes:
      - ./SmartMarketPlace_backend:/smp-back
    ports:
      - "5432:5432"